apiVersion: v1
kind: Service
metadata:
  name: dbx
  labels:
    app: dbx
spec:
  selector:
    app: dbx
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
